language: ruby
sudo: false
rvm: 2.2.0
script: bundle exec rake deploy
env:
  global:
  - secure: RZr4F0GOI/Cv5l7q3hkmZyUofhgZi2yz+Gjseuw4y+inil1t0LaviQEOocHNpXK8QZL8Z9T49zwY6jCr8IhH2oiqdQHuxG68M6NRs3dNVrIoKmdBaLcietvLOez3FSCqPJ8qZueY8c9Uu/NSDkqsLJSruW49Zdm6xZntuZKywUi14y4Yf4vJ2u7Ksjy/I13VChqL8ZomJ8Q58KbO1HqsnN0QlF+mM2dASbanLoa1kyAGpSVkcZxwQQrU7H8A9BkTcacW5KXkrGVxlmFPaUJGh5vZPaeXuGP0ECWyto+infOaxtCCO8oSiIVfkUcbjfSGTWV5/lwODqVwxv78szf5REmWrigcBpBJokG3MhItEzzAGvMn/5Amp/w6l6EViveY27qiWYMh5sy1o9PhylKmB5Zwef+IfUevHVXNCo7/6Z74RLTquRAbDt9XfFQoNG3iKl+7Xfyh/sJ5fGQiqs3a94lK5rDpYaMQejKaYz6L58q6lQa2/0PoYNBTda0SAgp+XS8BrGLRtWjAk5osq925+jQpMWEZrh/mMYC44GCYerp+nFYheNEJZSFlySjJhJX/6XmU6WmGFAjh1W6/PVfT1C8wT622u4U4LplxPj2wQBf2nXV+Cen64AmIw04iR9++9mgHlaX3Hz9Il8AWhgJzwcMNVOGZGy/1RB8RoVG4V5A=
